_0:
  _target_: toolz.functoolz.identity
  _partial_: true
_1:
  _target_: helio_tools._src.editors.load.load_fits_to_map
  _partial_: true
_2:
  _target_: helio_tools._src.editors.scale.normalize_radius
  _partial_: true
  resolution: 2048
  crop: true
  padding_factor: 0.1
_3:
  _target_: helio_tools._src.editors.calibration.correct_degregation
  _partial_: true
  method: auto
_4:
  _target_: helio_tools._src.editors.datastructure.map_to_ndarray
  _partial_: true
_5:
  _target_: helio_tools._src.editors.scale.normalize_fn
  _partial_: true
  fn:
    _target_: astropy.visualization.mpl_normalize.ImageNormalize
    _partial_: false
    vmin: 0
    vmax: 8800
    clip: true
    stretch:
      _target_: astropy.visualization.stretch.AsinhStretch
      _partial_: false
      a: 0.001
_6:
  _target_: einops.einops.rearrange
  _partial_: true
  pattern: H W -> H W 1
  H: 2048
  W: 2048
